name = input ('Enter your name : ')
num = 5
print()
print(name * num)
print("Show Triangle")
print (num * "*")
print ( (num-1) * "*")
print ( (num-2) * "*")
print ( (num-3) * "*")
print ( (num-4) * "*")
