s = input('Enter string : ')
print()
print("String is alpha = ", s.isalpha())
print("String is alpha and numeric = ", s.isalpha())
print("String is numeric = ", s.isnumeric())
print("String is decimal = ", s.isdecimal())
print("String is digic = ", s.isdigit())
print("String is lower = ", s.islower())
print("String is upper = ", s.isupper())
print("String is space = ", s.isspace())
print("String is title = ", s.istitle())
 
